version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    image: stat
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  stats-db:
    image: postgres:14.6-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  service:
    build: main
    image: main
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/main-db

  db:
    image: postgres:14.6-alpine
    container_name: main_db
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
