CREATE TABLE IF NOT EXISTS HITS
(
    ID          BIGINT generated by default as identity primary key,
    APP         VARCHAR(64) NOT NULL,
    URI         VARCHAR(300) NOT NULL,
    IP          VARCHAR(30) NOT NULL,
    TIMESTAMP   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);